name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BABY_BOT_D8EF9 }}
        run: firebase use baby-bot-d8ef9
        # run: firebase functions:config:set stripe.secret="your-stripe-secret-key" twilio.account_sid="your-twilio-account-sid" twilio.auth_token="your-twilio-auth-token"

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BABY_BOT_D8EF9 }}
        run: firebase deploy --only functions --token $FIREBASE_TOKEN
